variables:
  - name: _TeamName
    value: DotNetCore

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - main

pr:
  autoCancel: false
  branches:
    include:
    - '*'

# The public PR pool schema is different from the 1ES one. We use 'vmImage' which is a default azure pipeline schema. 'os' and 'name' have nothing to do with image selection here.
# 1ES uses 'image' but defining an image this way using our public pools duseOneEngineeringPool not work as they aren't configured this way.
# We can later add the flag 'useOneEngineeringPool' or one engineering system: false or true in all tasks to determine if we use vmImage or a 1es pool object.
parameters:
- name: pools
  type: object
  default:
  - name: NetCore-Public
    vmImage: windows-latest
    os: windows
    emoji: 🪟
    rid: win-x64
  - name: NetCore-Public
    vmImage: windows-latest
    os: windows
    emoji: 🤖
    rid: win-arm64
  - name: NetCore-Public
    vmImage: ubuntu-latest
    os: linux
    emoji: 🐧
  - name: NetCore-Public
    vmImage: macOS-latest
    os: macOS
    emoji: 💪
    rid: osx-arm64
  - name: NetCore-Public
    vmImage: macOS-latest
    os: macOS
    emoji: 🍎
    rid: osx-x64

stages:
- stage: o # o is just used so it looks like a bullet point in the output of devops
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enableTelemetry: true
      helixRepo: dotnet/cli-lab
      timeoutInMinutes: 180 # increase timeout since BAR publishing might wait a long time
      jobs:
      - ${{ each image in parameters.pools }}:
        - template: build-test.yml
          parameters:
            pool:
              vmImage: ${{ image.vmImage }}
              os: ${{ image.os }}
              emoji: ${{ image.emoji }}
              rid: ${{ image.rid }}
            useOneEngineeringPool: false
          variables:
          - name: _OfficialBuildArgs
            value: ''
          strategy:
            matrix:
              Debug:
                _BuildConfig: Debug
                _SignType: none
                _DotNetPublishToBlobFeed: false
                _BuildArgs:

              Release:
                _BuildConfig: Release
                _SignType: none
                _DotNetPublishToBlobFeed: false
                _BuildArgs: